### ISSUE TITLE
AttributeError: module 'dlib' has no attribute 'correlation_tracker'

### ISSUE THREAD

**Issue by syedbuzzy** [saimj7/People-Counting-in-Real-Time#11]
the video starts each time i try to run the code..but it stop as soon as the people in the video touches the line...please help

C:\Users\User\Desktop\test3>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
[INFO] Starting the video..
Traceback (most recent call last):
  File "C:\Users\User\Desktop\test3\run.py", line 345, in <module>
    run()
  File "C:\Users\User\Desktop\test3\run.py", line 159, in run
    tracker = dlib.correlation_tracker()
AttributeError: module 'dlib' has no attribute 'correlation_tracker'
![WhatsApp Image 2021-02-05 at 2 57 34 PM](https://user-images.githubusercontent.com/78585182/107000261-89e90c00-67c2-11eb-9954-bd30d9eb3890.jpeg)

C:\Users\User\Desktop\test3>

**Comment by saimj7** [comment]
did you install dlib?

**Comment by syedbuzzy** [comment]
Im getting this error while installing dlib .. visual c++ is already installed on my system tho...

Microsoft Windows [Version 10.0.19041.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\User>pip install dlib
Collecting dlib
  Using cached dlib-19.21.1.tar.gz (3.6 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-8b44ww9i'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\python\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\build\lib.win-amd64-3.9 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!




  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 223, in <module>
      setup(
    File "c:\python\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "c:\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\python\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\python\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-hgpz4aj8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\dlib'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\
    Complete output (60 lines):
    running install
    running build
    running build_py
    package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\python\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\build\lib.win-amd64-3.9 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:5 (message):



      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


      You must use Visual Studio to build a python extension on windows.  If you
      are getting this error it means you have not installed Visual C++.  Note
      that there are many flavors of Visual Studio, like Visual Studio for C#
      development.  You need to install Visual Studio for C++.


      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!




    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 223, in <module>
        setup(
      File "c:\python\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\User\AppData\Local\Temp\pip-install-dlt3_6mk\dlib_f47bee40ebca446e92a7b4d30e03969f\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\python\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\python\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-dlt3_6mk\\dlib_f47bee40ebca446e92a7b4d30e03969f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-hgpz4aj8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\dlib' Check the logs for full command output.

C:\Users\User>

**Comment by saimj7** [comment]
You need to install visual studio build tools, windows 10 sdk add ons from your visual studio installer

**Comment by syedbuzzy** [comment]
problem solved sir ...tq so much...

**Comment by 0breaker** [comment]
> the video starts each time i try to run the code..but it stop as soon as the people in the video touches the line...please help
> 
> C:\Users\User\Desktop\test3>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
> [INFO] Starting the video..
> Traceback (most recent call last):
> File "C:\Users\User\Desktop\test3\run.py", line 345, in
> run()
> File "C:\Users\User\Desktop\test3\run.py", line 159, in run
> tracker = dlib.correlation_tracker()
> AttributeError: module 'dlib' has no attribute 'correlation_tracker'
> ![WhatsApp Image 2021-02-05 at 2 57 34 PM](https://user-images.githubusercontent.com/78585182/107000261-89e90c00-67c2-11eb-9954-bd30d9eb3890.jpeg)
> 
> C:\Users\User\Desktop\test3>

Same error please, dlib is installed but i get this error every time

**Comment by saimj7** [comment]
Can you tell me how did you install dlib and its version?

**Comment by saran-23** [comment]
I'm facing legacy-install-failure when  i try to install dlib, also i have already installed cmake using 'pip install cmake' my operating system win 11 and also installed vs build tools
