### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jatinanand0** [saimj7/People-Counting-in-Real-Time#12]
I am trying to done below code in google colab and getting the error.. can you please help
!python Run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4

[INFO] Starting the video..
: cannot connect to X server

**Comment by saimj7** [comment]
Sorry, no colab support at the moment

**Comment by EhrenLeAwesome** [comment]
I have been getting the same issue running the plain example in Docker. Maybe there is something that I am missing?
```
# Dockerfile

# pull the official docker image
FROM ubuntu:latest

# set work directory
WORKDIR /src

# We don't want to interact with this container during setup
ENV DEBIAN_FRONTEND=noninteractive 

# Update the linux ppackages
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install wget -y

# Install all ubunutu python dependancies
RUN apt-get install build-essential cmake -y
RUN apt-get install libopenblas-dev liblapack-dev -y
RUN apt-get install libx11-dev libgtk-3-dev -y
RUN apt-get install python3 python3-dev python3-pip -y

# install project requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .

# Run the project
CMD [\
    "python3", \
    "Run.py", \
    "--prototxt=mobilenet_ssd/MobileNetSSD_deploy.prototxt", \
    "--model=mobilenet_ssd/MobileNetSSD_deploy.caffemodel", \
    "--input=videos/example_01.mp4"\
    ]
```

**Comment by EhrenLeAwesome** [comment]
I was able to find the solution to my problem. The issue in my container was that I had no virtual desktop env set up in my Dockerfile. This post helped me quite a bit. Hope this helps! https://stackoverflow.com/questions/39840184/python-code-crashes-with-cannot-connect-to-x-server-when-detaching-sshtmux-se
