### ISSUE TITLE
Program not working on ip camera 

### ISSUE THREAD

**Issue by kundanbind** [saimj7/People-Counting-in-Real-Time#13]
Hello sir, when using on webcam the program is running but when using ip camera there is an error related to imutils resize

**Comment by kundanbind** [comment]
How to use ip camera

**Comment by saimj7** [comment]
Can you post the error

**Comment by kundanbind** [comment]
frame = imutils.resize(frame, width = 500)
		rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

		# if the frame dimensions are empty, set them
		if W is None or H is None:
			(H, W) = frame.shape[:2]
it cannot draw frame

**Comment by saimj7** [comment]
I cannot see the error, please paste the traceback

**Comment by kundanbind** [comment]
Sir which company's ip ip camera you used 
I am using dahua's company ip camera but its not working please tell about which type of ip camera i will use

**Comment by saimj7** [comment]
It doesn't matter as long as it supports streaming over protocols like rtsp, http, etc. I have used Hikvision.

**Comment by kundanbind** [comment]
I am attaching the snapshot of the error while accessing ip camera in your application. I am also attaching configuration file screenshot and rest of the config  is by default.

![2021-02-15 (1)](https://user-images.githubusercontent.com/78973188/107927893-9f69ed00-6f9d-11eb-8d37-128d0412e2df.png)
![2021-02-15](https://user-images.githubusercontent.com/78973188/107927901-a2fd7400-6f9d-11eb-9ced-c5078342b6f2.png)

**Comment by saimj7** [comment]
Try adding /video at the end of your url `(e.g., url = 'http://191.138.0.100:8040/video')`

**Comment by saimj7** [comment]
Try adding /video at the end of your url (e.g., url = 'http://191.138.0.100:8040/video') and you also need to enter the port (8040 is the port). Usually, you can find the port from your IP camera url.
