### ISSUE TITLE
Error importing Scipy module

### ISSUE THREAD

**Issue by sw-dev-code** [saimj7/People-Counting-in-Real-Time#14]
I've installed Python modules according to the README instructions, but when I run the `Run.py` script getting the following error:

```
ubuntu@jetson:~/People-Counting-in-Real-Time$ python Run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel
Traceback (most recent call last):
  File "Run.py", line 1, in <module>
    from mylib.centroidtracker import CentroidTracker
  File "/home/ubuntu/People-Counting-in-Real-Time/mylib/centroidtracker.py", line 2, in <module>
    from scipy.spatial import distance as dist
ImportError: No module named scipy.spatial
```

**Comment by saimj7** [comment]
Try `pip install scipy==1.4.1`

**Comment by sw-dev-code** [comment]
@saimj7 Thank you, that issue is solved. Now I'm getting the following error `Illegal instruction (core dumped)`.

Can you tell me more about it and what can be the problem?

**Comment by saimj7** [comment]
Maybe something to do with Ubuntu? Note that this is intended for Windows at the moment.

**Comment by sw-dev-code** [comment]
@saimj7 Can you please send me the versions of scipy and numpy you are using? The result of your python - m pip freeze would be helpful. I figured it out that scipy is still a problem on Ubuntu.

**Comment by saimj7** [comment]
Sure, python 3.7.4, numpy 1.19.2 and, scipy 1.4.1

**Comment by sw-dev-code** [comment]
Thank you, I got it working somehow without using `imshow` on JetsonNano. It would be nice to update the `requirements.txt` file with module versions, you can do it by running `pip freeze > requirements.txt.` This is just a suggestion, once more, thank you.
