### ISSUE TITLE
Error  when set Thread = True in config

### ISSUE THREAD

**Issue by wisnuanggara** [saimj7/People-Counting-in-Real-Time#15]
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
VIDEOIO ERROR: V4L: can't open camera by index 0

When I'm not using Thread/Thread=False, everything goes smoothly.
Run with raspberry pi 4 with Logitech 920 webcam

**Comment by saimj7** [comment]
Try this, before line 331 add:
```
if config.Thread:
  vs.release()
```
In threading class, add this function:
```
def release(self):
  return self.cap.release()
```

The problem could be in releasing the camera device/resource, hence the error resource busy.
