### ISSUE TITLE
why showing this error?

### ISSUE THREAD

**Issue by uckiran98** [saimj7/People-Counting-in-Real-Time#16]
usage: Run.py [-h] [-p PROTOTXT] -m MODEL [-i INPUT] [-o OUTPUT]
              [-c CONFIDENCE] [-s SKIP_FRAMES]
Run.py: error: the following arguments are required: -m/--model

**Comment by saimj7** [comment]
Did you use `python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4`

**Comment by uckiran98** [comment]
now the code is working
