### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by tamikazi** [saimj7/People-Counting-in-Real-Time#17]
I'm getting multiple errors at the "Preparing wheel metadata" step

**Comment by saimj7** [comment]
While installing what requirement?

**Comment by tamikazi** [comment]
I am getting an error when I go to run the test script with centroid tracker:
ImportError: No module named mylib.centroidtracker

Even though I've installed centroid tracker successfully?

**Comment by tamikazi** [comment]
Do you think this could be used to count insects? For example, ants walking across the threshold line?

**Comment by saimj7** [comment]
It only works if the detector is trained on insects dataset. You should also consider the camera fov, diversity (include different lighting conditions, variations etc.,) in your datasets.
