### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by BMNassnet** [saimj7/People-Counting-in-Real-Time#18]
i have this error in runtame
PS C:\Users\usr> python C:\Users\usr\OneDrive\Bureau\People-Counting-in-Real-Time-master/run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
Traceback (most recent call last):
  File "C:\Users\usr\OneDrive\Bureau\People-Counting-in-Real-Time-master\run.py", line 349, in <module>
    run()
  File "C:\Users\usrs\OneDrive\Bureau\People-Counting-in-Real-Time-master\run.py", line 42, in run
    net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wvn_it83\opencv\modules\dnn\src\caffe\caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "mobilenet_ssd/MobileNetSSD_deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'

**Comment by saimj7** [comment]
Did you install the libraries according to `requirements.txt?`

**Comment by BMNassnet** [comment]
yes I have installed it well  scipy ,schedule ,numpy, argparse ,imutils, dlib and opencv

**Comment by saimj7** [comment]
What are their versions?

**Comment by BMNassnet** [comment]
imutlis 0.5.4
dlib 19.22.0
schedule1.10.0
numpu 1.20.2
argparse 1.4.0
opencv-python 4.5.1
scipy 1.6.3

**Comment by BMNassnet** [comment]
thanks man  i just found
my version of argparse was bad

thank you so much

**Comment by akks29** [comment]
my argparse version is correct..still getting the same error.

**Comment by akks29** [comment]
what should be done?
