### ISSUE TITLE
Total people inside value not accurate

### ISSUE THREAD

**Issue by 0xPYTHONIC** [saimj7/People-Counting-in-Real-Time#19]
As i can see in that example, when those first couples (2 people holding hands) are exiting, the "total people inside" value is not changing but the "exit" value is. Why is that?
Am i missing something?
EDIT: I reviewed the code and i saw the "total people inside" value is getting refreshed and is totally ok after someone is entering.
But why not just "inside = totalDown-totalUp"? 
The var "inside" could get negativ, so we just need to implement following: 
if totalup is equal to totaldown, just don't increment totalup.
Because obviously someone entered somewhere else, or the system didn't recognized the person. 

Btw. if a person has been counted and returns back in the counter direction without leaving the picture, is he getting counted?

**Comment by saimj7** [comment]
True, atm counting is built on the assumption that people entered would leave sooner or later (consider a simple retail store with 1 entrance). One of the reasons we could also choose to run 24/7. People would be counted when they cross the border wrt the camera field of view.
