### ISSUE TITLE
error while running on pi4

### ISSUE THREAD

**Issue by zaanen** [saimj7/People-Counting-in-Real-Time#2]
hello,

i get the following error when running on a pi4 
anny idea what it can be? also is it possible to run on a webcam instead of an ip camera? would love to monitor the occupancy at our sporclub with this.

Traceback (most recent call last):
  File "Run.py", line 1, in <module>
    from mylib.centroidtracker import CentroidTracker
  File "/home/pi/Downloads/People-Counting-in-Real-Time-master/mylib/centroidtracker.py", line 2, in <module>
    from scipy.spatial import distance as dist
  File "/home/pi/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 98, in <module>
    from .qhull import *
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by saimj7** [comment]
Hi, change line 47 to `vs = VideoStream(0).start()` for webcam. I did not run this on a pi but it might be something to do with atlas. The following might fix your issue:

- https://github.com/Kitt-AI/snowboy/issues/262

- https://raspberrypi.stackexchange.com/questions/111877/problem-running-scikit-learn-on-raspberry-pi

**Comment by zaanen** [comment]
Thanks saimj7 i got it working now. it had something to do rasbperry pi and using python3 and pip3
installed all the necesarry libaries he asked with pip3. 

now i have to workout the speed on the raspberry and had a monitoring tryout from horizontal view. but then the movement was to fast to determine human so processor power of the arm processor.

I also think that your counting total in latest scripts is in the if statement of down  only at the moment,

Thanks for all the help.

**Comment by saimj7** [comment]
Great, thanks. We simply take the difference between down and up for the total count.

**Comment by mniang04** [comment]
> Merci saimj7, je l'ai fait fonctionner maintenant. Il avait quelque chose à faire rasbperry pi et en utilisant python3 et pip3a installé toutes les bibliothèques nécessaires qu'il a demandées avec pip3. > > maintenant, je dois entraîner la vitesse sur la framboise et j'ai eu un essai de surveillance à partir de la vue horizontale. mais ensuite le mouvement était trop rapide pour déterminer la puissance humaine du processeur du processeur du bras. > > Je pense également que votre total de comptage dans les derniers scripts est dans l'énoncé if de down seulement pour le moment, > > Merci pour toute l'aide. 


bonjour, comment ça s'est passé
I have the same problem

**Comment by mniang04** [comment]
Hello, how you resolve it 
I've the same problem with my raspberry pi3
