### ISSUE TITLE
.py to .exe issue

### ISSUE THREAD

**Issue by UcanLahana** [saimj7/People-Counting-in-Real-Time#20]
Hi i'm trying convert this porject to executable. Pyinstaller doesn't support the -prototxt and -model input arguments while runtime line. Can i add this lines to config file or inside of the script?

**Comment by saimj7** [comment]
You can hardcode the path, e.g., comment out lines 19, 20, and anything associated with them: `args["prototxt"]` would be the file path on your disk: `'mobilenet_ssd/MobileNetSSD_deploy.prototxt'` .

**Comment by UcanLahana** [comment]
I solved it as you said. Thanks
