### ISSUE TITLE
Error while testing on Windows 10

### ISSUE THREAD

**Issue by nikolacrnicrni** [saimj7/People-Counting-in-Real-Time#3]
When I run the code 
`python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4`
It starts the video, but as soon the person gets to the line, everything crashes with error:

> [INFO] Starting the video..
> Traceback (most recent call last):
>   File "run.py", line 345, in <module>
>     run()
>   File "run.py", line 160, in run
>     rect = dlib.rectangle(startX, startY, endX, endY)
> Boost.Python.ArgumentError: Python argument types in
>     rectangle.__init__(rectangle, numpy.int32, numpy.int32, numpy.int32, numpy.int32)
> did not match C++ signature:
>     __init__(struct _object * __ptr64, long left, long top, long right, long bottom)
>     __init__(struct _object * __ptr64)

**Comment by saimj7** [comment]
Thinking that could be a problem with dlib installation. Did you install /build it with `pip install dlib`? I believe you also need cmake and visual studio to build it on Windows.

**Comment by nikolacrnicrni** [comment]
Yes, I had problems with dlib. So I downloaded some older version.
I had visual studio and cmake installed on my computer, but it still didn't work.

**Comment by saimj7** [comment]
What is your dlib version and how did you install it? Mine is `19.18.0`.

**Comment by nikolacrnicrni** [comment]
19.5.1

**Comment by saimj7** [comment]
Ok, let's do a reinstall with `pip install dlib', can you let me know if any errors? Make sure to uninstall the existing dlib version first.

**Comment by nikolacrnicrni** [comment]
It works now. I updated the visual studio too. Thanks

**Comment by saimj7** [comment]
Great, thanks.
