### ISSUE TITLE
Issue in Tracking people and reassigning of new id to the same people

### ISSUE THREAD

**Issue by rishabh316** [saimj7/People-Counting-in-Real-Time#31]
Hey, i am running this counter on the cctv footage of my office and this counter is assigning different ids to the same person again and again when they comes in the frame, is there any solution to this problem? Your reply is awaited.

**Comment by saimj7** [comment]
Hi, as you see we are just counting persons and do not remember their features, so it will actually count everyone. One idea I can think of is assigning unique ID's per person but then we should also work on the accuracy of our data, model.  The top-down view is hard to identify unique persons. One example: [https://stackoverflow.com/questions/20145076/pedestrian-detection-with-unique-identifier](url)

**Comment by rishabh316** [comment]
yeah you were right about the accuracy of top down view. Should i use Kalman filter for detection or to improve accuracy or what other solution might help? And thanks for the reply sir.

**Comment by saimj7** [comment]
No straightforward answer, I guess you should go with trial and error, find the approach that performs the best :)
