### ISSUE TITLE
Windows & Mac

### ISSUE THREAD

**Issue by Aljaber808** [saimj7/People-Counting-in-Real-Time#32]
I have tested on my windows 10 PC and its working great, but I tested on Mac and it is  not working as it should be, as the counter is getting reset to 0  each time a person is a crossing the line. any help please?

**Comment by saimj7** [comment]
That's weird, maybe something to do with its dependencies? I have no idea about Mac unfortunately

**Comment by Aljaber808** [comment]
Got it to work.. 👍🏻
