### ISSUE TITLE
IP Camera

### ISSUE THREAD

**Issue by bbartling** [saimj7/People-Counting-in-Real-Time#38]
Hi,

Can anyone recommend me a particular IP camera make and manufacture that could be used for this? 

Also then on the LAN I would need a computer or virtual machine right? Any recommended OS for this?

Thanks!

**Comment by saimj7** [comment]
Something that supports basic networking protocols e.g., TCP/IP, HTTP, RTSP etc. I've used Hikvision, TP-Link before.

Are you planning to have it wired/wireless? You need a computer in either case, not confident about VMs though. I would suggest Windows but feel free to experiment!

**Comment by bbartling** [comment]
Thanks for the incite on the IP cameras that work with open CV, I've only dabbled with web cams. 

For what its worth I am trying to incorporate [a BACnet protocol API ](https://github.com/bbartling/bacnet-people-counter/blob/develop/pyimagesearch/people_counter_bacnet.py)to the pyimagesearch code. At least in North America on typical building control systems, BACnet protocol is very popular. So hopefully testing this out this summer to have a people counting script with a discoverable BACnet object of the total people count. Its only something useful on a LAN where people count data can be useful, like what we are using it for is the HVAC system. So basically the HVAC system can discover/know how many people are in the building to save on electricity bills.

Hit me up if you would be interested in a fork or collaborating with BACnet there is free Python libraries for it. Cheers...
