### ISSUE TITLE
Jetson nano : not getting streaming

### ISSUE THREAD

**Issue by Mony24** [saimj7/People-Counting-in-Real-Time#39]
1. Video streaming working fine. nvcc --version responded fine.
2. People-counting working fine with demo video.
3. Not starting video streaming getting following error.
[INFO] Starting the live stream..
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

Both cap_gstreamer.cpp and cap.cpp file copied in created folder file path --/home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/ . Please help/inform, how to make use of it and make it working.

**Comment by saimj7** [comment]
Unfortunately I have no idea about Nano, have you tried posting a thread here? https://forums.developer.nvidia.com/t/jetson-nano-faq/82953

**Comment by Mony24** [comment]
Please inform me how to make use of *.cpp file at following location with this program. At without this file same error message we are getting. 
/home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp
Requested forum will not help and not contain required information.

**Comment by Mony24** [comment]
Good Morning.
Thanks for your response.

Please inform me how to make use of *.cpp file at the following location
with this program. Without this file also the same error message we are
getting. Requested forum will not help.
/home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp

Please help to figure this out and solve this issue.
Thanks & Regards

**Comment by 1997wzk** [comment]
@Mony24 hello ,my device is also a jetson nano,did you run it successfully.

**Comment by saimj7** [comment]
Hi, I cannot debug this as I do not have a Nano. I would definitely start by posting a thread under their official support https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76, make sure to check the tags and post under correct tag e.g., gstreamer/camera/opencv etc.
