### ISSUE TITLE
Issue in real time ip camera tracking

### ISSUE THREAD

**Issue by AdityaDarke2** [saimj7/People-Counting-in-Real-Time#41]
Hi, I am getting this error when I run the ip camera command, I hope you reply quickly 

Edit: now i am getting this error : 
[INFO] Starting the live stream..
[ERROR:0@1.079] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.1.7:4747/video in function 'cv::icvExtractPattern'

[ERROR:0@3.641] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.1.7:4747/video in function 'cv::icvExtractPattern'

**Comment by saimj7** [comment]
Does it work if you have your url as http://192.168.1.7:4747 instead?
