### ISSUE TITLE
issue with caffemodel and function

### ISSUE THREAD

**Issue by Yessine360** [saimj7/People-Counting-in-Real-Time#43]
Hello, when i execute i get this error 
do you know how to fix it by any chance? 
C:\Users\msi>python C:\Users\msi\Desktop\People-Counting-in-Real-Time-master\run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
Traceback (most recent call last):
  File "C:\Users\msi\Desktop\People-Counting-in-Real-Time-master\run.py", line 353, in <module>
    run()
  File "C:\Users\msi\Desktop\People-Counting-in-Real-Time-master\run.py", line 42, in run
    net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "mobilenet_ssd/MobileNetSSD_deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'

**Comment by JAOT** [comment]
I would suggest you run the the file while in the directory of the run.py file.

Apparently, it's lookin for the video with a path relative to where you are?

**Comment by Yessine360** [comment]
still same error unfortunately :/
C:\Users\msi>cd C:\Users\msi\Desktop\People-Counting-in-Real-Time-master

C:\Users\msi\Desktop\People-Counting-in-Real-Time-master>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
Traceback (most recent call last):
  File "run.py", line 353, in <module>
    run()
  File "run.py", line 42, in run
    net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "mobilenet_ssd/MobileNetSSD_deploy.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile'

**Comment by Yessine360** [comment]
> I would suggest you run the the file while in the directory of the run.py file.
> 
> Apparently, it's lookin for the video with a path relative to where you are?

nvm it worked now, thanks <3
