### ISSUE TITLE
Reducing the frame Size of the camera feed.

### ISSUE THREAD

**Issue by Sudip-star-a11y** [saimj7/People-Counting-in-Real-Time#45]
Hi Saimj7,

Superb Work!!. Really appreciable.

One help I require on how to reduce the camera frame size? Like I am getting the live feed from the camera but in my actual deployment I don't want the entire feed to be involved in people counting. I would like to trim out the four edges of the live feed square.

Will really appreciate your help.

Thanks.

**Comment by saimj7** [comment]
Hi, try resizing the width on line 100:

`frame = imutils.resize(frame, width = 500)`
