### ISSUE TITLE
Mail Alert stops code from running

### ISSUE THREAD

**Issue by XxXxNooBxXxX** [saimj7/People-Counting-in-Real-Time#55]
How can I make the mail alert not stop the code from running, while also sending me an email whenever the number of people goes over the threshold?

**Comment by saimj7** [comment]
We need to use a background thread to send the alerts, fixed in this [commit](https://github.com/saimj7/People-Counting-in-Real-Time/commit/95351a2271ebb77b890ef3bf0be2fa803bc4decd)
