### ISSUE TITLE
Need help to insert "Enter/Exit" and "Total People Inside" in mysql Database

### ISSUE THREAD

**Issue by towhidulkhan** [saimj7/People-Counting-in-Real-Time#58]
Hi,

 i was trying to take real time count data (Enter/Exit" and "Total People Inside) and insert it in mysql database, but failed. It will be appreciable if you help me in this regard and let me know where i have to make changes.

Thanks,

Towhidul

**Comment by saimj7** [comment]
Hi, this project does not support mysql. Maybe if you can show me where you have failed in your implementation, I can try to help you out
