### ISSUE TITLE
Timing of logs

### ISSUE THREAD

**Issue by ea-juinius** [saimj7/People-Counting-in-Real-Time#60]
Hi, please advise how you can make the log file more detailed. I mean, how can I make the input/output to time reference in the log file?

**Comment by saimj7** [comment]
Hi, do you mean adding datetime info to input/output?

**Comment by ea-juinius** [comment]
Yes, it would be great for analytics. What time did the person enter

**Comment by saimj7** [comment]
Sure, added a simple logic to track the datetime along with the person move_in/move_out data. You can download the updated log and check it out

**Comment by ea-juinius** [comment]
There is a small problem, the data is not written to csv.
And can you please make the time of arrival only by time was? 
Sorry, I'm a bit of a student and do not understand everything

**Comment by ea-juinius** [comment]
It almost worked, but I can't figure out how to link log_time to move_in

**Comment by saimj7** [comment]
You don't really need to link log_time to the remaining data as it's not meant to be (it just shows the end time when the log is saved). You can ignore it and if you only need move_in and time data, it is enough to change these lines:

line 46:```def log_data(move_in):```
line 49: ```data = [move_in]```
line 63: ```wr.writerow(("(Move In, Time)", ""))```
line 319: ```log_data(move_in)```

**Comment by ea-juinius** [comment]
Yes, I did. But I don't understand how I can separate the data 
so that move_in from Time will be separate

**Comment by saimj7** [comment]
Implemented in this [commit](https://github.com/saimj7/People-Counting-in-Real-Time/commit/2263d1d16840d974efc02ea7eb95f2721e08831e)

**Comment by ea-juinius** [comment]
Thank you! That's just what I needed! Have a great day!
