### ISSUE TITLE
m/--model

### ISSUE THREAD

**Issue by Dipanshu010** [saimj7/People-Counting-in-Real-Time#63]
#usage: people_counter.py [-h] [-p PROTOTXT] -m MODEL [-i INPUT] [-o OUTPUT] [-c CONFIDENCE] [-s SKIP_FRAMES]
people_counter.
![Screenshot 2023-06-05 194923](https://github.com/saimj7/People-Counting-in-Real-Time/assets/83054544/89b630e0-6c48-4b03-b266-ea1e757c12a1)
py: error: the following arguments are required: -m/--model

**Comment by m-marcjanik** [comment]
You did not specify any arguments. Look back into readme.

**Comment by 2012215** [comment]
Alright. so I am trying to do the project and it shows this: 
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/a7152a6e-9074-47f8-8aa5-ba0bc70c9790)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/793cfb71-bcdf-4c8b-9873-efd65b4d037f)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/1da785b3-7529-4d92-83e1-6a8a271b3fb6)

**Comment by m-marcjanik** [comment]
Edit requirements.txt and move cmake to the first place and then run installing dependencies again.

**Comment by 2012215** [comment]
After editing the txt file this is showing:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/fae2481e-0fe8-4263-a497-3fcb15f26313)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/b8aa4767-a285-4c7f-839d-268830a2399a)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/b487f3ee-2d14-409a-bff0-83483f1a83e0)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/dc7ae46b-13c8-4c20-ad8a-708b7e42e7aa)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/428cb076-56c0-4cb5-b78a-20b029416143)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/d6dc8b96-52eb-440b-bed3-2761a960c5b0)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/6b3c0751-1392-4f73-8b46-c7ba55c01cb3)

**Comment by 2012215** [comment]
I don't understand what seems to be the problem. But it is not resolving it. It shows "Building dlib" failed.

**Comment by 2012215** [comment]
The error comes at "Building dlib".

**Comment by 2012215** [comment]
I also tried running the same command on Spyder. It shows the same error as in the VS code above.

**Comment by m-marcjanik** [comment]
Please refer to the information from error message you posted - it quite clearly states how to solve the problem.

**Comment by 2012215** [comment]
It is the C++ thing right?

**Comment by 2012215** [comment]
Okay. So the requirement.txt file worked Now this is coming: 
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/748d497b-ac0a-4f49-a7a0-1c3f313f8640)

**Comment by 2012215** [comment]
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/7a932f70-b3a4-4c17-aa17-ed268b85637f)
This one is in Spyder Notebook.

**Comment by m-marcjanik** [comment]
Check if all the folders (detector / tracker / utils) are in the place with contents as in the original repo.

**Comment by 2012215** [comment]
I downloaded the zip file as it was given in the repo. All the folders are in place with contents.
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/a32d6b77-7953-4720-a703-b99b3226f8e7)

**Comment by 2012215** [comment]
I really need to work this project out But it doesn't run:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/1f16dae3-ef1c-4fe0-a031-6b57bc0c1dda)
All the folders are in place with the contents.
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/660e33ae-2fe6-41f3-b84c-8b445fa866d7)
 What do I do to fix it?. Chat gpt say to install tracker which is already installed.

**Comment by m-marcjanik** [comment]
There is some issue with importing TrackableObject function from tracker folder and trackableobject.py file. Check if the file contains function definition. If yes - try moving function definition directly to the code.

**Comment by 2012215** [comment]
The trackableobject.py contains function definition. I tried it moving that piece of code into people_counter.py but it is still not working. Same error occurs.

**Comment by m-marcjanik** [comment]
Did you remove import line after moving that definition into main code file?

**Comment by 2012215** [comment]
After removing the import line:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/7f1f37e8-52a6-437a-a767-e1481709c571)

**Comment by m-marcjanik** [comment]
Please check if the python version (python --version or python3 --version) matches the one used by the creator of repo (3.11.3). I did use it with python 3.9 and 3.10. Also check (pip list) if the versions match those in requirements.txt.

**Comment by 2012215** [comment]
Its 3.8.5. I'm installing 3.11.3

**Comment by 2012215** [comment]
After Updating everything this oocurs:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/b2578425-f1d4-423b-8ed2-094d5ccdcea2)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/783961aa-5c03-4b65-9b21-571d59b0e3fe)

**Comment by m-marcjanik** [comment]
Show me your pip list

**Comment by 2012215** [comment]
Why are there only 2?
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/bd7e3a96-53f3-4e8d-b027-9b98bc2d06de)

**Comment by m-marcjanik** [comment]
Necessary requirements from requirements.txt are not installed on your instance. First install cmake (pip install cmake) and then follow with pip install -r requirements.txt

**Comment by 2012215** [comment]
Ok

**Comment by 2012215** [comment]
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/8742b207-00fd-42b8-a2ad-58922267f72c)
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/373d7106-6724-4a1c-9dd9-01d388295b58)

**Comment by 2012215** [comment]
Ok so after such a long time the list is done:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/af398d9f-9e23-4d81-a9d6-f9968c852b77)
But then this comes:
![image](https://github.com/saimj7/People-Counting-in-Real-Time/assets/75359546/cadb85e2-b8d2-4acb-a272-ea4c3ef8fcf9)

**Comment by 2012215** [comment]
It's working. The project worked.
Thank you so much for the help. Appreciate it

**Comment by m-marcjanik** [comment]
> It's working. The project worked.
> Thank you so much for the help. Appreciate it

Glad I could help, and I hope you have fun!

**Comment by Dipanshu010** [comment]
Hey, can you please reupload this project I’m finding some difficulties in it  Sent from Mail for Windows From: 2012215Sent: 28 June 2023 18:48To: saimj7/People-Counting-in-Real-TimeCc: Dipanshu010; AuthorSubject: Re: [saimj7/People-Counting-in-Real-Time] m/--model (Issue #63) It's working. The project worked.Thank you so much for the help. Appreciate itGlad I could help, and I hope you have fun!And I'm sorry to bother you or caused you any kind of discomfort.Thank you once again—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
