### ISSUE TITLE
Not Running 

### ISSUE THREAD

**Issue by naturobotic** [saimj7/People-Counting-in-Real-Time#7]
python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel

gives:
python: can't open file 'run.py': [Errno 2] No such file or directory

when replaced with Run.py can't access the libraries and gives:

Traceback (most recent call last):
  File "Run.py", line 1, in <module>
    from mylib.centroidtracker import CentroidTracker
ImportError: No module named mylib.centroidtracker

**Comment by saimj7** [comment]
Hi, you need to be inside the repo directory and then run it.

**Comment by naturobotic** [comment]
It occurs inside the directory.

**Comment by naturobotic** [comment]
all good. 

Is there a way to use the Rpi Camera, USB camera lags a lot, and when treading set to  True it doesn't start giving the error: 
[ WARN:0] global /home/pi/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video1): can't open camera by index

**Comment by saimj7** [comment]
At the moment, this is only configured for PC.
