### ISSUE TITLE
launch using CUDA

### ISSUE THREAD

**Issue by isakimov** [saimj7/People-Counting-in-Real-Time#71]
Hello! I'm trying to run a counter with CUDA to take the load off the CPU
Installed all the necessary dependencies (CUDA, CuDNN, torch, torchvision, torchaudio), torch.cuda.is_available() returns True, but when people-counter.py is run, the process is not displayed in nvidia-smi. 
In gpustat I see that all the load goes to the CPU.
Has anyone managed to do this?

**Comment by jasonjiang8866** [comment]
you need to compile opencv against CUDA
