### ISSUE TITLE
not woking for webcam

### ISSUE THREAD

**Issue by lokabhiram** [saimj7/People-Counting-in-Real-Time#76]
It not working for webcam
error:
PS C:\Users\abhi\Downloads\People-Counting-in-Real-Time-master> python people_counter.py --prototxt detector/MobileNetSSD_deploy.prototxt --model detector/MobileNetSSD_d
eploy.caffemodel                                                                                                                                                                        [INFO] Starting the live stream..
Traceback (most recent call last):
  File "C:\Users\abhi\Downloads\People-Counting-in-Real-Time-master\people_counter.py", line 367, in <module>
    people_counter()
  File "C:\Users\abhi\Downloads\People-Counting-in-Real-Time-master\people_counter.py", line 136, in people_counter
    frame = imutils.resize(frame, width = 500)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhi\anaconda3\Lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Thivish16** [comment]
Hi @lokabhiram , did you by any chance solve this issue?
I am facing the same issue. It would be great if you could help in resolving this. Thanks!

**Comment by lokabhiram** [comment]
> Hi @lokabhiram , did you by any chance solve this issue?
> I am facing the same issue. It would be great if you could help in resolving this. Thanks!

Problem solved.. In config.json,  add 0 without quotes. url:0

**Comment by Thivish16** [comment]
That worked. Thanks a lot!
